name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Install dependencies
      uses: poojamanjare/CompositeActions@main

    - name: run depedencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
